# Generated by Django 6.1.1 on 2026-09-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
        ('books', '0006_book_assembly_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField(blank=True, default=dict, verbose_name='المستند')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='الإصدار')),
                ('origin', models.CharField(choices=[('assembly', 'التجميع'), ('editor', 'المحرّر')], default='assembly', max_length=10, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّلت في')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript', to='books.book', verbose_name='الكتاب')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts', to='assembly.assemblyrun', verbose_name='تشغيل التجميع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'مخطوطة',
                'verbose_name_plural': 'المخطوطات',
            },
        ),
        migrations.CreateModel(
            name='ManuscriptSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField(blank=True, default=dict, verbose_name='المستند')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='الإصدار')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('reason', models.CharField(choices=[('reassembly', 'قبل إعادة التجميع'), ('manual', 'يدوية')], default='manual', max_length=12, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='editor.manuscript', verbose_name='المخطوطة')),
            ],
            options={
                'verbose_name': 'نسخة محفوظة من المخطوطة',
                'verbose_name_plural': 'النسخ المحفوظة من المخطوطات',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
