# Generated by Django 6.1.1 on 2026-09-25 01:11

import django.db.models.deletion
import editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_assembly_settings'),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptsnapshot',
            name='reason',
            field=models.CharField(choices=[('reassembly', 'قبل إعادة التجميع'), ('manual', 'يدوية'), ('edit', 'قبل تعديل آلي')], default='manual', max_length=12, verbose_name='السبب'),
        ),
        migrations.CreateModel(
            name='StyleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim', models.CharField(choices=[('17x24', '17×24 سم'), ('a4', 'A4'), ('a5', 'A5'), ('b5', 'B5'), ('14x21', '14×21 سم'), ('12x17', '12×17 سم'), ('custom', 'مقاس مخصّص')], default='17x24', max_length=10, verbose_name='القطع')),
                ('width_mm', models.FloatField(default=170.0, verbose_name='العرض (مم)')),
                ('height_mm', models.FloatField(default=240.0, verbose_name='الارتفاع (مم)')),
                ('top_mm', models.FloatField(default=20.0, verbose_name='الهامش العلوي (مم)')),
                ('bottom_mm', models.FloatField(default=22.0, verbose_name='الهامش السفلي (مم)')),
                ('inner_mm', models.FloatField(default=22.0, verbose_name='الهامش الداخلي (مم)')),
                ('outer_mm', models.FloatField(default=18.0, verbose_name='الهامش الخارجي (مم)')),
                ('bleed_mm', models.FloatField(default=0.0, verbose_name='زيادة القص (مم)')),
                ('body_font', models.CharField(default='amiri', max_length=40, verbose_name='خط المتن')),
                ('latin_font', models.CharField(default='times', max_length=40, verbose_name='الخط اللاتيني')),
                ('heading_font', models.CharField(default='amiri', max_length=40, verbose_name='خط العناوين')),
                ('body_size_pt', models.FloatField(default=13.0, verbose_name='حجم خط المتن (نقطة)')),
                ('line_height', models.FloatField(default=1.7, verbose_name='تباعد الأسطر')),
                ('indent_em', models.FloatField(default=1.5, verbose_name='إزاحة أول السطر (em)')),
                ('heading_scale', models.JSONField(blank=True, default=editor.models.default_heading_scale, verbose_name='أحجام العناوين')),
                ('footnote_size_pt', models.FloatField(default=10.0, verbose_name='حجم خط الحواشي (نقطة)')),
                ('footnote_numbering', models.CharField(choices=[('page', 'حسب الصفحة'), ('chapter', 'حسب الفصل'), ('book', 'حسب الكتاب')], default='page', max_length=10, verbose_name='ترقيم الحواشي')),
                ('running_header', models.CharField(choices=[('none', 'بلا ترويسة'), ('book', 'عنوان الكتاب'), ('chapter', 'عنوان الفصل')], default='chapter', max_length=10, verbose_name='الترويسة')),
                ('page_number', models.CharField(choices=[('none', 'بلا ترقيم'), ('bottom_center', 'أسفل الصفحة في الوسط'), ('bottom_outer', 'أسفل الصفحة في الطرف الخارجي'), ('top_outer', 'أعلى الصفحة في الطرف الخارجي')], default='bottom_center', max_length=15, verbose_name='رقم الصفحة')),
                ('chapter_opening', models.CharField(choices=[('any', 'أي صفحة'), ('recto', 'صفحة فردية')], default='any', max_length=10, verbose_name='بداية الفصل')),
                ('front_matter', models.JSONField(blank=True, default=editor.models.default_front_matter, verbose_name='الصفحات التمهيدية')),
                ('print_source_pages', models.BooleanField(default=False, verbose_name='أرقام الصفحات الأصلية في الهامش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stylesheet', to='books.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'تنسيق كتاب',
                'verbose_name_plural': 'تنسيقات الكتب',
            },
        ),
    ]
