# Generated by Django 6.1.1 on 2026-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_stylesheet_snapshot_reason_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='keep_headings',
            field=models.BooleanField(default=True, verbose_name='العنوان مع السطر التالي'),
        ),
        migrations.AddField(
            model_name='stylesheet',
            name='orphans',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='أقل عدد من الأسطر أسفل الصفحة'),
        ),
        migrations.AddField(
            model_name='stylesheet',
            name='widows',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='أقل عدد من الأسطر أعلى الصفحة'),
        ),
    ]
