# Generated by Django 6.1.1 on 2026-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_stylesheet_widows_orphans_keep_headings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesheet',
            name='running_header',
            field=models.CharField(choices=[('none', 'بلا ترويسة'), ('book', 'عنوان الكتاب'), ('chapter', 'عنوان الفصل')], default='none', max_length=10, verbose_name='الترويسة'),
        ),
    ]
