# Generated by Django 6.1.1 on 2026-09-26 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_page_reading'),
        ('editor', '0004_running_header_default_none'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='base',
            field=models.JSONField(blank=True, null=True, verbose_name='أصل التحرير'),
        ),
        migrations.AddField(
            model_name='manuscriptsnapshot',
            name='base',
            field=models.JSONField(blank=True, null=True, verbose_name='أصل التحرير'),
        ),
        migrations.CreateModel(
            name='ChangesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_version', models.PositiveIntegerField(default=0, verbose_name='إصدار المخطوطة')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد التجميع'), ('done', 'اكتمل'), ('error', 'خطأ')], default='queued', max_length=10, verbose_name='الحالة')),
                ('pages', models.JSONField(blank=True, null=True, verbose_name='الصفحات المطلوبة')),
                ('plan', models.JSONField(blank=True, default=dict, verbose_name='المقارنة')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='نتائج المقارنة')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهت في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_plans', to='books.book', verbose_name='الكتاب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='طلبها')),
            ],
            options={
                'verbose_name': 'مقارنة تغييرات المراجعة',
                'verbose_name_plural': 'مقارنات تغييرات المراجعة',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('book',), name='changes_plan_one_active_per_book')],
            },
        ),
    ]
