# Generated by Django 6.1.1 on 2026-09-26 23:02

import django.db.models.deletion
import editor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_page_reading'),
        ('editor', '0005_base_changes_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=editor.models.book_image_path, verbose_name='الملف')),
                ('sha256', models.CharField(max_length=64, verbose_name='بصمة الملف')),
                ('width', models.PositiveIntegerField(verbose_name='العرض (بكسل)')),
                ('height', models.PositiveIntegerField(verbose_name='الارتفاع (بكسل)')),
                ('format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG')], max_length=4, verbose_name='الصيغة')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('purpose', models.CharField(choices=[('cover', 'غلاف'), ('body', 'صورة في المتن')], default='cover', max_length=10, verbose_name='الغرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='رُفعت في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book', verbose_name='الكتاب')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='رفعها')),
            ],
            options={
                'verbose_name': 'صورة كتاب',
                'verbose_name_plural': 'صور الكتب',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('book', 'sha256'), name='book_image_unique_sha256')],
            },
        ),
    ]
