# Generated by Django 6.1.1 on 2026-09-23 23:39

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_cut', models.FloatField(blank=True, null=True, verbose_name='حدّ الترويسة')),
                ('footnote_line', models.FloatField(blank=True, null=True, verbose_name='خط الحاشية')),
                ('page_number_zone', models.CharField(choices=[('none', 'بدون'), ('top', 'أعلى الصفحة'), ('bottom', 'أسفل الصفحة')], default='bottom', max_length=8, verbose_name='موضع رقم الصفحة')),
                ('page_number_height', models.FloatField(default=0.06, verbose_name='ارتفاع منطقة رقم الصفحة')),
                ('source', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي')], default='auto', max_length=8, verbose_name='المصدر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّلت في')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='books.book', verbose_name='الكتاب')),
                ('reference_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.page', verbose_name='الصفحة المرجعية')),
            ],
            options={
                'verbose_name': 'أدلة التخطيط',
                'verbose_name_plural': 'أدلة التخطيط',
            },
        ),
        migrations.CreateModel(
            name='Preprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField(default=0, verbose_name='زاوية التدوير')),
                ('skew_confidence', models.FloatField(default=0, verbose_name='ثقة تقدير الانحراف')),
                ('border_crop', models.JSONField(blank=True, default=list, verbose_name='قص الحواف الداكنة')),
                ('crop_box', models.JSONField(blank=True, default=list, verbose_name='صندوق القص')),
                ('bg_kernel', models.IntegerField(default=0, verbose_name='نواة تسوية الخلفية')),
                ('nlm_h', models.IntegerField(default=6, verbose_name='قوة إزالة التشويش')),
                ('sauvola_window', models.IntegerField(default=41, verbose_name='نافذة Sauvola')),
                ('sauvola_k', models.FloatField(default=0.2, verbose_name='معامل Sauvola')),
                ('is_manual', models.BooleanField(default=False, verbose_name='معدّلة يدويًا')),
                ('auto_params', models.JSONField(blank=True, default=dict, verbose_name='القيم التلقائية')),
                ('gray_image', models.FileField(blank=True, upload_to=core.storage.page_derived_path, verbose_name='الصورة الرمادية')),
                ('bw_image', models.FileField(blank=True, upload_to=core.storage.page_derived_path, verbose_name='الصورة بالأبيض والأسود')),
                ('display_image', models.FileField(blank=True, upload_to=core.storage.page_derived_path, verbose_name='صورة العرض')),
                ('thumbnail', models.FileField(blank=True, upload_to=core.storage.page_derived_path, verbose_name='الصورة المصغّرة')),
                ('output_width', models.PositiveIntegerField(default=0, verbose_name='عرض الناتج')),
                ('output_height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع الناتج')),
                ('line_boxes', models.JSONField(blank=True, default=list, verbose_name='صناديق الأسطر')),
                ('median_line_height', models.FloatField(default=0, verbose_name='ارتفاع السطر الوسيط')),
                ('n_lines', models.PositiveIntegerField(default=0, verbose_name='عدد الأسطر')),
                ('footnote_rule_y', models.IntegerField(blank=True, null=True, verbose_name='موضع خط الحاشية')),
                ('edge_strips_removed', models.JSONField(blank=True, default=list, verbose_name='أشرطة الحافة المُزالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّلت في')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocess', to='books.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'معالجة أولية',
                'verbose_name_plural': 'المعالجات الأولية',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('body', 'متن'), ('heading', 'عنوان'), ('running_header', 'ترويسة'), ('page_number', 'رقم الصفحة'), ('footnote', 'حاشية'), ('poetry', 'شعر'), ('other', 'أخرى')], max_length=20, verbose_name='النوع')),
                ('bbox', models.JSONField(default=list, verbose_name='الإحداثيات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('source', models.CharField(choices=[('guides', 'من الأدلة'), ('auto', 'تلقائي'), ('manual', 'يدوي')], default='guides', max_length=8, verbose_name='المصدر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='books.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['page', 'order'],
            },
        ),
    ]
