# Generated by Django 6.1.1 on 2026-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocess',
            name='manual_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='القيم اليدوية'),
        ),
    ]
