# Generated by Django 6.1.1 on 2026-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_preprocess_manual_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocess',
            name='footnote_block_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='بداية كتلة الحاشية'),
        ),
        migrations.AddField(
            model_name='preprocess',
            name='page_number_box',
            field=models.JSONField(blank=True, null=True, verbose_name='موضع رقم الصفحة المكتشف'),
        ),
    ]
