# Generated by Django 6.1.1 on 2026-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_page_detection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layoutguides',
            options={'verbose_name': 'التخطيط العام', 'verbose_name_plural': 'التخطيط العام'},
        ),
        migrations.AlterField(
            model_name='region',
            name='source',
            field=models.CharField(choices=[('guides', 'من التخطيط'), ('auto', 'تلقائي'), ('manual', 'يدوي')], default='guides', max_length=8, verbose_name='المصدر'),
        ),
    ]
