# Generated by Django 6.1.1 on 2026-09-23 23:39

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='المؤلف')),
                ('original_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة النشر الأصلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('source_pdf', models.FileField(upload_to=core.storage.book_source_path, verbose_name='ملف PDF')),
                ('has_text_layer', models.BooleanField(null=True, verbose_name='يحوي طبقة نصية')),
                ('source_page_count', models.PositiveIntegerField(default=0, verbose_name='عدد صفحات الملف')),
                ('skip_first', models.PositiveSmallIntegerField(default=0, verbose_name='تجاوز الصفحات الأولى')),
                ('skip_last', models.PositiveSmallIntegerField(default=0, verbose_name='تجاوز الصفحات الأخيرة')),
                ('pages_per_sheet', models.PositiveSmallIntegerField(choices=[(1, 'صفحة واحدة'), (2, 'صفحتان')], default=1, verbose_name='صفحات في كل ورقة')),
                ('split_ratio', models.FloatField(default=0.5, verbose_name='موضع القص')),
                ('use_text_layer', models.BooleanField(default=True, verbose_name='استخدام الطبقة النصية')),
                ('digit_style', models.CharField(choices=[('western', 'أرقام غربية (0-9)'), ('arabic_indic', 'أرقام عربية هندية (٠-٩)')], default='western', max_length=20, verbose_name='نمط الأرقام')),
                ('status', models.CharField(choices=[('uploaded', 'مرفوع'), ('processing', 'قيد المعالجة'), ('needs_guides', 'بانتظار ضبط الأدلة'), ('ocr', 'قيد التعرّف على النص'), ('ready_for_review', 'جاهز للمراجعة'), ('reviewing', 'قيد المراجعة'), ('assembled', 'مُجمَّع'), ('error', 'خطأ')], default='uploaded', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الصفحة')),
                ('source_index', models.PositiveIntegerField(verbose_name='رقم الصفحة في الملف')),
                ('source_half', models.CharField(choices=[('full', 'كاملة'), ('right', 'النصف الأيمن'), ('left', 'النصف الأيسر')], default='full', max_length=8, verbose_name='جزء الورقة')),
                ('split_ratio_override', models.FloatField(blank=True, null=True, verbose_name='موضع القص لهذه الصفحة')),
                ('original_image', models.FileField(blank=True, upload_to=core.storage.page_original_path, verbose_name='الصورة الأصلية')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='العرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='الارتفاع')),
                ('dpi', models.FloatField(default=0, verbose_name='الدقة')),
                ('status', models.CharField(choices=[('uploaded', 'مرفوعة'), ('preprocessed', 'مُعالَجة'), ('layout_done', 'تم التخطيط'), ('ocr_done', 'تم التعرّف'), ('reviewed', 'مُراجَعة'), ('assembled', 'مُجمَّعة'), ('error', 'خطأ'), ('excluded', 'مستثناة')], default='uploaded', max_length=20, verbose_name='الحالة')),
                ('error_from', models.CharField(blank=True, max_length=40, verbose_name='مرحلة الخطأ')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المهمة')),
                ('attention_flags', models.JSONField(blank=True, default=list, verbose_name='إشارات الانتباه')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='مستثناة')),
                ('text_layer_text', models.TextField(blank=True, verbose_name='نص الطبقة النصية')),
                ('guides_override', models.JSONField(blank=True, null=True, verbose_name='أدلة خاصة بالصفحة')),
                ('provisional_text', models.TextField(blank=True, verbose_name='النص المبدئي')),
                ('final_text', models.TextField(blank=True, verbose_name='النص النهائي')),
                ('text_state', models.CharField(choices=[('none', 'لا نص'), ('provisional', 'نص مبدئي'), ('final', 'نص نهائي')], default='none', max_length=20, verbose_name='حالة النص')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='رُوجعت في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books.book', verbose_name='الكتاب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pages', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['book', 'number'],
                'unique_together': {('book', 'number')},
            },
        ),
    ]
