# Generated by Django 6.1.1 on 2026-09-24 08:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scan_thumbnail',
            field=models.FileField(blank=True, upload_to=core.storage.page_scan_thumb_path, verbose_name='مصغّرة المسح'),
        ),
    ]
