# Generated by Django 6.1.1 on 2026-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_page_scan_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='printed_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرقم المطبوع'),
        ),
    ]
