# Generated by Django 6.1.1 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_page_printed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='n_unresolved',
            field=models.PositiveIntegerField(default=0, verbose_name='كلمات غير محسومة'),
        ),
    ]
