# Generated by Django 6.1.1 on 2026-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_backfill_n_unresolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='assembly_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='إعدادات التجميع'),
        ),
    ]
