# Generated by Django 6.1.1 on 2026-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_assembly_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='awaits_ocr_start',
            field=models.BooleanField(default=False, verbose_name='بانتظار «بدء المعالجة»'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('uploaded', 'مرفوع'), ('processing', 'قيد التخطيط'), ('needs_guides', 'تم التخطيط'), ('ocr', 'قيد المعالجة'), ('ready_for_review', 'جاهز للمراجعة'), ('reviewing', 'قيد المراجعة'), ('assembled', 'مُجمَّع'), ('error', 'خطأ')], default='uploaded', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='page',
            name='guides_override',
            field=models.JSONField(blank=True, null=True, verbose_name='تخطيط خاص بالصفحة'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('uploaded', 'مرفوعة'), ('preprocessed', 'مُجهَّزة'), ('layout_done', 'بانتظار التعرّف'), ('ocr_done', 'تم التعرّف'), ('reviewed', 'مُراجَعة'), ('assembled', 'مُجمَّعة'), ('error', 'خطأ'), ('excluded', 'مستثناة')], default='uploaded', max_length=20, verbose_name='الحالة'),
        ),
    ]
