# Generated by Django 6.1.1 on 2026-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_awaits_ocr_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='reading',
            field=models.JSONField(blank=True, default=dict, verbose_name='القراءة'),
        ),
    ]
