# Generated by Django 6.1.1 on 2026-10-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_page_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='run_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بدأ تشغيل المعالجة في'),
        ),
        migrations.AddField(
            model_name='page',
            name='run_token',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='تشغيل المعالجة الجاري'),
        ),
        migrations.AlterField(
            model_name='book',
            name='use_text_layer',
            field=models.BooleanField(default=False, verbose_name='استخدام الطبقة النصية'),
        ),
    ]
