# Generated by Django 6.1.1 on 2026-10-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_fonts_templates'),
        ('books', '0009_page_run_claim_text_layer_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='accounts.organization', verbose_name='المؤسسة'),
        ),
    ]
