# Generated by Django 6.1.1 on 2026-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=40, verbose_name='الجزء'),
        ),
    ]
