# Generated by Django 6.1.1 on 2026-10-03 02:39

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_groups'),
        ('books', '0009_page_run_claim_text_layer_off'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير المؤسسة'), ('member', 'عضو')], default='member', max_length=10, verbose_name='الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُضيف في')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('family', models.CharField(max_length=200, verbose_name='العائلة في الملف')),
                ('regular', models.FileField(max_length=255, upload_to=accounts.models.org_font_path, verbose_name='الملف العادي')),
                ('bold', models.FileField(blank=True, max_length=255, upload_to=accounts.models.org_font_path, verbose_name='الملف العريض')),
                ('italic', models.FileField(blank=True, max_length=255, upload_to=accounts.models.org_font_path, verbose_name='الملف المائل')),
                ('bold_italic', models.FileField(blank=True, max_length=255, upload_to=accounts.models.org_font_path, verbose_name='الملف العريض المائل')),
                ('files', models.JSONField(blank=True, default=dict, verbose_name='بيانات الملفات')),
                ('latin', models.BooleanField(default=False, verbose_name='فيه حروف لاتينية وأرقام')),
                ('arabic', models.BooleanField(default=True, verbose_name='فيه حروف عربية')),
                ('licence', models.TextField(blank=True, verbose_name='الترخيص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='رُفع في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='حُذف في')),
                ('licence_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أقرّ بالترخيص')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='accounts.organization', verbose_name='المؤسسة')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حذفه')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'خط مؤسسة',
                'verbose_name_plural': 'خطوط المؤسسات',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['organization', 'removed_at'], name='org_font_active')],
            },
        ),
        migrations.CreateModel(
            name='StyleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='القيم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_templates', to='accounts.organization', verbose_name='المؤسسة')),
                ('source_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.book', verbose_name='أُخذ من الكتاب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حدّثه')),
            ],
            options={
                'verbose_name': 'قالب تنسيق',
                'verbose_name_plural': 'قوالب التنسيق',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='style_template_unique_name')],
            },
        ),
    ]
