# Generated by Django 6.1.1 on 2026-10-04 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_default_organization'),
        ('books', '0010_book_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('pages', models.PositiveIntegerField(verbose_name='الصفحات')),
                ('validity_days', models.PositiveIntegerField(default=365, verbose_name='الصلاحية (أيام)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('active', models.BooleanField(default=True, verbose_name='متاحة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['pages', 'id'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='البلد'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('organization', 'مؤسسة'), ('individual', 'فرد')], default='organization', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('publisher', 'دار نشر'), ('research', 'مركز بحث'), ('university', 'جامعة'), ('library', 'مكتبة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المؤسسة'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unlimited',
            field=models.BooleanField(default=False, verbose_name='رصيد غير محدود'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name='الموقع'),
        ),
        migrations.CreateModel(
            name='QuotaGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signup', 'رصيد التسجيل'), ('purchase', 'شراء'), ('bonus', 'هدية'), ('trial', 'تجربة'), ('adjustment', 'تسوية')], default='purchase', max_length=20, verbose_name='النوع')),
                ('pages', models.PositiveIntegerField(verbose_name='الصفحات')),
                ('remaining', models.PositiveIntegerField(verbose_name='المتبقي')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='يبدأ في')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='العملة')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='المرجع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُضيف في')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُلغي في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضافه')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_grants', to='accounts.organization', verbose_name='الحساب')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='accounts.plan', verbose_name='الباقة')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
            ],
            options={
                'verbose_name': 'رصيد ممنوح',
                'verbose_name_plural': 'الأرصدة الممنوحة',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grant', 'منح'), ('consume', 'قراءة صفحة'), ('expire', 'انتهاء الصلاحية'), ('revoke', 'إلغاء'), ('adjust', 'تسوية')], max_length=10, verbose_name='النوع')),
                ('pages', models.IntegerField(verbose_name='الصفحات')),
                ('run_key', models.CharField(blank=True, max_length=64, verbose_name='التشغيل')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='في')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.book', verbose_name='الكتاب')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_entries', to='accounts.organization', verbose_name='الحساب')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.page', verbose_name='الصفحة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='accounts.quotagrant', verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'قيد رصيد',
                'verbose_name_plural': 'سجل الرصيد',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotaHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(blank=True, max_length=64, verbose_name='التشغيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='حُجز في')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_holds', to='accounts.organization', verbose_name='الحساب')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_hold', to='books.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'صفحة محجوزة',
                'verbose_name_plural': 'الصفحات المحجوزة',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='سُجّل في')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='أُكّد البريد في')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
            },
        ),
        migrations.AddIndex(
            model_name='quotagrant',
            index=models.Index(fields=['organization', 'expires_at'], name='quota_grant_org_expiry'),
        ),
        migrations.AddIndex(
            model_name='quotaentry',
            index=models.Index(fields=['organization', 'kind', 'created_at'], name='quota_entry_org_kind'),
        ),
        migrations.AddConstraint(
            model_name='quotaentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'consume')), fields=('page', 'run_key'), name='quota_consume_once'),
        ),
    ]
