# Generated by Django 6.1.1 on 2026-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_email_is_the_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='overdraft_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='حد السحب على المكشوف (صفحات)'),
        ),
    ]
