# Generated by Django 6.1.1 on 2026-09-24 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_page_n_unresolved'),
        ('ocr', '0002_line_is_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('resolve', 'حسم كلمة'), ('edit', 'تعديل سطر'), ('insert', 'إدراج سطر'), ('delete', 'حذف سطر'), ('approve', 'اعتماد'), ('reopen', 'إعادة فتح')], max_length=10, verbose_name='الإجراء')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='بعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='في')),
                ('undone', models.BooleanField(default=False, verbose_name='تُراجع عنه')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='ocr.line', verbose_name='السطر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='books.page', verbose_name='الصفحة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعديل مراجعة',
                'verbose_name_plural': 'سجل المراجعة',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
