# Generated by Django 6.1.1 on 2026-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerevision',
            name='action',
            field=models.CharField(choices=[('resolve', 'حسم كلمة'), ('edit', 'تعديل سطر'), ('insert', 'إدراج سطر'), ('delete', 'حذف سطر'), ('merge', 'دمج كلمتين'), ('drop_word', 'حذف كلمة'), ('approve', 'اعتماد'), ('reopen', 'إعادة فتح')], max_length=10, verbose_name='الإجراء'),
        ),
    ]
