# Generated by Django 6.1.1 on 2026-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_revision_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerevision',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='الدفعة'),
        ),
        migrations.AlterField(
            model_name='linerevision',
            name='action',
            field=models.CharField(choices=[('resolve', 'حسم كلمة'), ('edit', 'تعديل سطر'), ('insert', 'إدراج سطر'), ('delete', 'حذف سطر'), ('merge', 'دمج كلمتين'), ('drop_word', 'حذف كلمة'), ('role', 'نوع السطر'), ('approve', 'اعتماد'), ('reopen', 'إعادة فتح'), ('gap', 'نص مقترح')], max_length=10, verbose_name='الإجراء'),
        ),
    ]
