# Generated by Django 6.1.1 on 2026-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_revision_batch_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerevision',
            name='action',
            field=models.CharField(choices=[('resolve', 'حسم كلمة'), ('edit', 'تعديل سطر'), ('insert', 'إدراج سطر'), ('delete', 'حذف سطر'), ('merge', 'دمج كلمتين'), ('drop_word', 'حذف كلمة'), ('role', 'نوع السطر'), ('approve', 'اعتماد'), ('reopen', 'إعادة فتح'), ('gap', 'نص مقترح'), ('fix', 'تصحيح في الكتاب')], max_length=10, verbose_name='الإجراء'),
        ),
    ]
