# Generated by Django 6.1.1 on 2026-10-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_page_run_claim_text_layer_off'),
        ('ocr', '0006_page_lookup_indexes'),
        ('review', '0005_revision_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerevision',
            name='page',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='books.page', verbose_name='الصفحة'),
        ),
        migrations.AddIndex(
            model_name='linerevision',
            index=models.Index(fields=['page', 'created_at', 'id'], name='revision_page_latest'),
        ),
    ]
