# Generated by Django 6.1.1 on 2026-09-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_book_assembly_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('book', 'الكتاب'), ('chapter', 'فصل')], default='book', max_length=10, verbose_name='النطاق')),
                ('chapter_id', models.CharField(blank=True, max_length=64, verbose_name='الفصل')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة المحتوى')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد الإخراج'), ('done', 'اكتمل'), ('error', 'خطأ'), ('cancelled', 'أُلغي')], default='queued', max_length=10, verbose_name='الحالة')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات')),
                ('first_page', models.PositiveIntegerField(default=1, verbose_name='رقم أول صفحة')),
                ('chapters', models.JSONField(blank=True, default=list, verbose_name='الفصول')),
                ('folder', models.CharField(blank=True, max_length=255, verbose_name='المجلد')),
                ('passes', models.PositiveSmallIntegerField(default=0, verbose_name='مرات الإخراج')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_renders', to='books.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'معاينة صفحات',
                'verbose_name_plural': 'معاينات الصفحات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['book', 'scope', 'chapter_id', '-created_at'], name='preview_scope_latest')],
            },
        ),
    ]
