# Generated by Django 6.1.1 on 2026-09-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_assembly_settings'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='المراجعة')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='الملف')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات')),
                ('chapters', models.JSONField(blank=True, default=list, verbose_name='الفصول')),
                ('manuscript_version', models.PositiveIntegerField(default=0, verbose_name='إصدار المخطوطة')),
                ('setup_hash', models.CharField(blank=True, max_length=64, verbose_name='بصمة التنسيق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
            ],
            options={
                'verbose_name': 'ترتيب صفحات الكتاب',
                'verbose_name_plural': 'ترتيبات صفحات الكتب',
            },
        ),
        migrations.AddField(
            model_name='previewrender',
            name='checks',
            field=models.JSONField(blank=True, default=list, verbose_name='ملاحظات الصفحات'),
        ),
        migrations.AddField(
            model_name='previewrender',
            name='images',
            field=models.BooleanField(default=True, verbose_name='صور الصفحات جاهزة'),
        ),
        migrations.AddField(
            model_name='previewrender',
            name='kind',
            field=models.CharField(choices=[('pages', 'صفحات'), ('layout', 'إعادة ترتيب')], default='pages', max_length=10, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='previewrender',
            name='result',
            field=models.JSONField(blank=True, default=dict, verbose_name='نتيجة إعادة الترتيب'),
        ),
        migrations.AddField(
            model_name='previewrender',
            name='version',
            field=models.PositiveIntegerField(default=0, verbose_name='إصدار المخطوطة'),
        ),
        migrations.AddIndex(
            model_name='previewrender',
            index=models.Index(fields=['book', 'kind', 'chapter_id', '-created_at'], name='preview_kind_latest'),
        ),
        migrations.AddField(
            model_name='livelayout',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publishing.previewrender', verbose_name='إخراج الكتاب الأساس'),
        ),
        migrations.AddField(
            model_name='livelayout',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_layout', to='books.book', verbose_name='الكتاب'),
        ),
    ]
