# Generated by Django 6.1.1 on 2026-09-26 02:46

import django.db.models.deletion
import publishing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_assembly_settings'),
        ('publishing', '0002_layout_and_live_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('docx', 'Word'), ('print_pdf', 'PDF للطباعة'), ('screen_pdf', 'PDF للشاشة'), ('epub', 'EPUB')], max_length=12, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد الإخراج'), ('done', 'اكتمل'), ('error', 'خطأ'), ('cancelled', 'أُلغي')], default='queued', max_length=10, verbose_name='الحالة')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='الخيارات')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='المدخلات')),
                ('manuscript_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='إصدار المخطوطة')),
                ('stylesheet_hash', models.CharField(blank=True, max_length=24, verbose_name='بصمة التنسيق')),
                ('renderer', models.CharField(blank=True, max_length=64, verbose_name='المُخرِج')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=publishing.models.export_path, verbose_name='الملف')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='الإحصاءات')),
                ('progress', models.JSONField(blank=True, default=dict, verbose_name='التقدّم')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='الملاحظات')),
                ('log', models.TextField(blank=True, verbose_name='السجل')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='books.book', verbose_name='الكتاب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أخرجه')),
            ],
            options={
                'verbose_name': 'إخراج',
                'verbose_name_plural': 'الإخراجات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['book', 'format', '-created_at'], name='export_book_format_latest')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('book', 'format'), name='export_one_active_per_format')],
            },
        ),
    ]
