# Generated by Django 6.1.1 on 2026-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewrender',
            name='status',
            field=models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد الترتيب'), ('done', 'اكتمل'), ('error', 'خطأ'), ('cancelled', 'أُلغي')], default='queued', max_length=10, verbose_name='الحالة'),
        ),
    ]
