# Generated by Django 6.1.1 on 2026-10-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0011_book_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم')),
                ('prefix', models.CharField(max_length=16, verbose_name='بداية المفتاح')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='بصمة المفتاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استعمال')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُلغي في')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مفتاح وصول',
                'verbose_name_plural': 'مفاتيح الوصول',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('body', 'المتن'), ('notes', 'الحواشي')], max_length=5, verbose_name='النوع')),
                ('words', models.JSONField(blank=True, default=list, verbose_name='الكلمات')),
                ('norm', models.TextField(blank=True, verbose_name='النص المطبَّع')),
                ('stamp', models.CharField(blank=True, max_length=80, verbose_name='بصمة الأسطر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.book', verbose_name='الكتاب')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='books.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'نص صفحة للبحث',
                'verbose_name_plural': 'نصوص الصفحات للبحث',
                'indexes': [models.Index(fields=['book', 'kind'], name='research_pagetext_book_kind')],
                'constraints': [models.UniqueConstraint(fields=('page', 'kind'), name='research_pagetext_page_kind')],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=40, verbose_name='الأداة')),
                ('status', models.CharField(choices=[('ok', 'ناجح'), ('error', 'خطأ'), ('limited', 'تجاوز الحد')], default='ok', max_length=8, verbose_name='الحالة')),
                ('ms', models.PositiveIntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='في')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='research.accesskey', verbose_name='المفتاح')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'استدعاء أداة',
                'verbose_name_plural': 'سجل استدعاءات الأدوات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['key', 'created_at'], name='research_toolcall_key_time')],
            },
        ),
    ]
