# Generated by Django 6.1.1 on 2026-09-23 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('bbox', models.JSONField(blank=True, null=True, verbose_name='الإحداثيات')),
                ('text', models.TextField(blank=True, verbose_name='النص')),
                ('ocr_text', models.TextField(blank=True, verbose_name='نص OCR الأصلي')),
                ('tokens', models.JSONField(blank=True, default=list, verbose_name='الكلمات')),
                ('confidence', models.FloatField(default=1.0, verbose_name='الثقة')),
                ('n_low', models.PositiveIntegerField(default=0, verbose_name='عدد الكلمات منخفضة الثقة')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='مُراجَع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.page', verbose_name='الصفحة')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='processing.region', verbose_name='المنطقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'سطر',
                'verbose_name_plural': 'الأسطر',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OcrRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=40, verbose_name='المحرّك')),
                ('model_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف النموذج')),
                ('model_revision', models.CharField(blank=True, max_length=64, verbose_name='إصدار النموذج')),
                ('backend', models.CharField(blank=True, max_length=20, verbose_name='المنصّة')),
                ('prompt', models.TextField(blank=True, verbose_name='التعليمة')),
                ('input_variant', models.CharField(blank=True, max_length=20, verbose_name='نوع الصورة المُدخلة')),
                ('raw_output', models.TextField(blank=True, verbose_name='الناتج الخام')),
                ('parsed_text', models.TextField(blank=True, verbose_name='النص المستخلص')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='المعاملات')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الرموز الناتجة')),
                ('finish', models.CharField(blank=True, max_length=20, verbose_name='سبب التوقف')),
                ('looped', models.BooleanField(default=False, verbose_name='تكرار مفرط')),
                ('status', models.CharField(choices=[('ok', 'ناجح'), ('error', 'خطأ')], default='ok', max_length=8, verbose_name='الحالة')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_runs', to='books.page', verbose_name='الصفحة')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_runs', to='processing.region', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'تشغيل OCR',
                'verbose_name_plural': 'تشغيلات OCR',
                'ordering': ['-created_at'],
            },
        ),
    ]
