# Generated by Django 6.1.1 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='أُدرج يدويًا'),
        ),
    ]
