# Generated by Django 6.1.1 on 2026-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_line_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='role',
            field=models.CharField(choices=[('body', 'محتوى'), ('heading', 'عنوان رئيسي'), ('subheading', 'عنوان فرعي')], default='body', max_length=12, verbose_name='نوع السطر'),
        ),
    ]
