# Generated by Django 6.1.1 on 2026-09-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_awaits_ocr_start'),
        ('ocr', '0003_line_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='role',
            field=models.CharField(choices=[('body', 'محتوى'), ('heading', 'عنوان رئيسي'), ('subheading', 'عنوان فرعي'), ('verse', 'شعر'), ('footnote', 'حاشية'), ('main', 'محتوى')], default='body', max_length=12, verbose_name='نوع السطر'),
        ),
        migrations.CreateModel(
            name='TextGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1, verbose_name='بعد الكلمة')),
                ('after_t', models.CharField(blank=True, max_length=200, verbose_name='نص الكلمة السابقة')),
                ('kind', models.CharField(choices=[('words', 'كلمات')], default='words', max_length=10, verbose_name='النوع')),
                ('text', models.TextField(verbose_name='النص المقترح')),
                ('source', models.CharField(default='secondary', max_length=20, verbose_name='المصدر')),
                ('support', models.FloatField(default=0.0, verbose_name='تأييد Tesseract')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('inserted', 'أُدرج'), ('dismissed', 'تُجوهل')], default='open', max_length=10, verbose_name='الحالة')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='حُسم في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حسمه')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps', to='ocr.line', verbose_name='السطر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='books.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'نص مقترح',
                'verbose_name_plural': 'نصوص مقترحة',
                'ordering': ['page', 'line__order', 'index', 'id'],
            },
        ),
    ]
