# Generated by Django 6.1.1 on 2026-10-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_page_reading"),
        ("ocr", "0004_roles_textgap"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُرسل في"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انتهى في"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("read", "قراءة"), ("ping", "فحص")],
                        default="read",
                        max_length=8,
                        verbose_name="العملية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "قيد التنفيذ"),
                            ("ok", "اكتمل"),
                            ("partial", "اكتمل جزئيًا"),
                            ("failed", "فشل"),
                            ("timeout", "انتهت المهلة"),
                            ("error", "تعذّر الاتصال"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "engines",
                    models.CharField(blank=True, max_length=80, verbose_name="النماذج"),
                ),
                (
                    "region_kind",
                    models.CharField(blank=True, max_length=20, verbose_name="المنطقة"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع الصورة"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نقطة النهاية"
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        verbose_name="رقم المهمة",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="حالة المهمة في Runpod"
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="آخر رمز HTTP"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="محاولات الإرسال"
                    ),
                ),
                (
                    "polls",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="مرات الاستعلام"
                    ),
                ),
                (
                    "queue_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="الانتظار وبدء العامل (مللي ثانية)",
                    ),
                ),
                (
                    "execution_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="التنفيذ على GPU (مللي ثانية)",
                    ),
                ),
                (
                    "total_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الزمن الكلي (مللي ثانية)"
                    ),
                ),
                (
                    "gpu",
                    models.CharField(blank=True, max_length=80, verbose_name="GPU"),
                ),
                (
                    "worker_id",
                    models.CharField(blank=True, max_length=80, verbose_name="العامل"),
                ),
                (
                    "worker_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="إصدار العامل"
                    ),
                ),
                (
                    "cold_start",
                    models.BooleanField(blank=True, null=True, verbose_name="بدء بارد"),
                ),
                (
                    "request",
                    models.JSONField(blank=True, default=dict, verbose_name="الطلب"),
                ),
                (
                    "response",
                    models.JSONField(blank=True, default=dict, verbose_name="الرد"),
                ),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_calls",
                        to="books.page",
                        verbose_name="الصفحة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب Runpod",
                "verbose_name_plural": "سجل طلبات Runpod",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
