# Generated by Django 6.1.1 on 2026-10-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_page_run_claim_text_layer_off'),
        ('ocr', '0005_remotecall'),
        ('processing', '0004_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='page',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.page', verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='ocrrun',
            name='page',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_runs', to='books.page', verbose_name='الصفحة'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['page', 'order'], name='ocr_line_page_order'),
        ),
        migrations.AddIndex(
            model_name='ocrrun',
            index=models.Index(fields=['page', 'engine_name'], name='ocr_run_page_engine'),
        ),
        migrations.AddIndex(
            model_name='ocrrun',
            index=models.Index(fields=['created_at'], name='ocr_run_created'),
        ),
    ]
