# Generated by Django 6.1.1 on 2026-09-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_book_assembly_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد التجميع'), ('done', 'اكتمل'), ('error', 'خطأ')], default='queued', max_length=10, verbose_name='الحالة')),
                ('stage', models.CharField(blank=True, choices=[('collect', 'جمع الأسطر'), ('paragraphs', 'بناء الفقرات'), ('seams', 'وصل الفقرات عبر الصفحات'), ('footnotes', 'ربط الحواشي'), ('headings', 'بناء العناوين'), ('typography', 'ضبط علامات الترقيم والأرقام'), ('save', 'حفظ المخطوطة')], max_length=20, verbose_name='المرحلة')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الخيارات')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='الملاحظات')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='الإحصاءات')),
                ('included', models.JSONField(blank=True, default=dict, verbose_name='الصفحات المُضمَّنة')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='المدة (مللي ثانية)')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_runs', to='books.book', verbose_name='الكتاب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بدأه')),
            ],
            options={
                'verbose_name': 'تشغيل تجميع',
                'verbose_name_plural': 'تشغيلات التجميع',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['book', '-created_at'], name='assembly_run_book_latest')],
            },
        ),
    ]
